default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: reddit_rss_development

test:
  <<: *default
  database: reddit_rss_test

production:
  <<: *default
  database: d5f9lndn3l6fck
  user: vqeonxehibwqmp
  password: fa4aa43fefa85689c3b2ce24a4a86ceba5031b8ea8a5644bb33b11dee2e72cb7
  host: ec2-54-243-253-17.compute-1.amazonaws.com
  port: 5432
