# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4145bfb8e5fecd637333e9733e0c3fdaa97cb6218dae710ae9e758265ed23263e64a60df6112f3d27e71cc1c3ca0895d5be044dea94b96d898b2c60fc61f0502

test:
  secret_key_base: bb49a4fa426dfa38db5382c5db1b012b4c21bec3c47f5a1120e6b6fe74d9fa66c5a8086fe349b96d657cb26513da6cfb17e894b6693acdda44ea2dc8d3be7cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
